import { Dispositivo, RecursoTecnico } from '../types';

export const initialDispositivos: Dispositivo[] = [
  {
    id: 1,
    marca: "Xiaomi",
    modelo: "Redmi Note 12 4G",
    procesador: "Snapdragon 685",
    chipset_id: "05c6:9008",
    created_at: "2026-06-20T10:00:00Z"
  },
  {
    id: 2,
    marca: "Samsung",
    modelo: "Galaxy A23 4G",
    procesador: "Snapdragon 680",
    chipset_id: "05c6:9008",
    created_at: "2026-06-20T10:15:00Z"
  },
  {
    id: 3,
    marca: "Motorola",
    modelo: "Moto G52",
    procesador: "Snapdragon 680",
    chipset_id: "05c6:9008",
    created_at: "2026-06-20T10:30:00Z"
  }
];

export const initialRecursosTecnicos: RecursoTecnico[] = [
  {
    id: 101,
    dispositivo_id: 1,
    tipo_recurso: "firehose",
    url_archivo: "https://tu-repositorio.com/files/prog_firehose_ddr_xiaomi_note12.elf",
    notas_tecnicas: "Cargador probado para salto de FRP en seguridad 2024-2026"
  },
  {
    id: 102,
    dispositivo_id: 1,
    tipo_recurso: "test_point",
    url_archivo: "https://tu-repositorio.com/images/xiaomi_note12_tp.jpg",
    notas_tecnicas: "Puntos ubicados abajo del conector de la batería, remover blindaje pequeño."
  },
  {
    id: 201,
    dispositivo_id: 2,
    tipo_recurso: "firehose",
    url_archivo: "https://tu-repositorio.com/files/prog_firehose_samsung_a23.elf",
    notas_tecnicas: "Presionar y mantener Vol+ y Vol- simultáneamente mientras se conecta el cable USB."
  },
  {
    id: 202,
    dispositivo_id: 2,
    tipo_recurso: "test_point",
    url_archivo: "https://tu-repositorio.com/images/samsung_a23_tp.jpg",
    notes: "Puntos ubicados en el sector medio izquierdo cerca al lector SIM. Requiere pinzas conductoras."
  } as any, // fallback
  {
    id: 301,
    dispositivo_id: 3,
    tipo_recurso: "firehose",
    url_archivo: "https://tu-repositorio.com/files/prog_firehose_moto_g52.elf",
    notas_tecnicas: "Cargador firmado por Lenovo. Permite flash de firmware completo."
  },
  {
    id: 302,
    dispositivo_id: 3,
    tipo_recurso: "test_point",
    url_archivo: "https://tu-repositorio.com/images/moto_g52_tp.jpg",
    notas_tecnicas: "Punto de prueba visible retirando la tapa plástica trasera, arriba a la derecha de la cámara."
  }
];

export const initialSqlSchema = `-- 1. Crear la tabla principal de dispositivos
CREATE TABLE dispositivos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    marca VARCHAR(50) NOT NULL,                  -- Ej: 'Xiaomi', 'Samsung'
    modelo VARCHAR(100) NOT NULL,                -- Ej: 'Redmi Note 12'
    procesador VARCHAR(50) NOT NULL,             -- Ej: 'Snapdragon 685', 'MT6765'
    chipset_id VARCHAR(50),                      -- Ej: 'SDM680' o ID de hardware (05c6:9008)
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 2. Crear la tabla de archivos técnicos (Firehose y Test Points)
CREATE TABLE recursos_tecnicos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    dispositivo_id BIGINT REFERENCES dispositivos(id) ON DELETE CASCADE,
    tipo_recurso VARCHAR(20) NOT NULL,           -- 'firehose', 'test_point', 'preloader'
    url_archivo TEXT NOT NULL,                   -- Enlace de descarga (p.ej., desde tu almacenamiento o GitHub)
    notas_tecnicas TEXT,                         -- Instrucciones extra ("Presionar Vol-", etc.)
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 3. Insertar un ejemplo real: Xiaomi Redmi Note 12
WITH nuevo_dispositivo AS (
    INSERT INTO dispositivos (marca, modelo, procesador, chipset_id)
    VALUES ('Xiaomi', 'Redmi Note 12 4G', 'Snapdragon 685', '05c6:9008')
    RETURNING id
)
INSERT INTO recursos_tecnicos (dispositivo_id, tipo_recurso, url_archivo, notas_tecnicas)
VALUES 
((SELECT id FROM nuevo_dispositivo), 'firehose', 'https://tu-repositorio.com/files/prog_firehose_ddr_xiaomi_note12.elf', 'Cargador probado para salto de FRP en seguridad 2024-2026'),
((SELECT id FROM nuevo_dispositivo), 'test_point', 'https://tu-repositorio.com/images/xiaomi_note12_tp.jpg', 'Puntos ubicados abajo del conector de la batería, remover blindaje pequeño.');`;
